#  ________  _________  ________  ________  ________      ___    ___ ___       ________  ________  ________      ___    ___
# |\   ____\|\___   ___\\   __  \|\   __  \|\   __  \    |\  \  /  /|\  \     |\   __  \|\   __  \|\   __  \    |\  \  /  /|
# \ \  \___|\|___ \  \_\ \  \|\  \ \  \|\  \ \  \|\  \   \ \  \/  / | \  \    \ \  \|\  \ \  \|\ /\ \  \|\ /_   \ \  \/  / /
#  \ \_____  \   \ \  \ \ \   __  \ \   _  _\ \   _  _\   \ \    / / \ \  \    \ \  \\\  \ \   __  \ \   __  \   \ \    / /
#   \|____|\  \   \ \  \ \ \  \ \  \ \  \\  \\ \  \\  \|   \/  /  /   \ \  \____\ \  \\\  \ \  \|\  \ \  \|\  \   \/  /  /
#     ____\_\  \   \ \__\ \ \__\ \__\ \__\\ _\\ \__\\ _\ __/  / /      \ \_______\ \_______\ \_______\ \_______\__/  / /
#    \|_________|   \|__|  \|__|\|__|\|__|\|__|\|__|\|__|\___/ /        \|_______|\|_______|\|_______|\|_______|\___/ /
#
# Support By StarryCountry Development 2021-2024
# Version: 1.4.0

#Spawn Location (Only Yaw, Please use /setWorldSpawn set spawn location)
yaw: 0

#Lobby Type
type: "Lobby"

#Void Settings (Set VoidTp or VoidLauncher)
isVoidTp: false
Void-Y: 30

#Anti WorldDownloader (If you don't want others to steal your map)
antiWDL: true

