name: StarryLobby
version: '1.7.3-Renascence'
main: cn.starry.hub.StarryLobby
authors: [ Stalyer ]
description: "Removed Inventory."
softdepend: [ AstralCore, PlayerPoints, LuckPerms, PlaceHolderAPI, ProtocolLib, Citizens, AuthMe, MasterControl ]
api-version: 1.21